"""listings photos amenities reviews

Revision ID: 0002
Revises: 0001
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('icon_key', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('listings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('location_label', sa.String(length=160), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('property_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('max_guests', sa.Integer(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('beds', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Double(), nullable=False),
    sa.Column('nightly_price_minor', sa.Integer(), nullable=False),
    sa.Column('cleaning_fee_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('archived_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("category IN ('beachfront', 'pools', 'cabins', 'amazing_views', 'countryside', 'lakefront', 'design', 'mansions', 'tiny_homes', 'trending')", name='ck_listings_category'),
    sa.CheckConstraint("currency = 'INR'", name='ck_listings_currency'),
    sa.CheckConstraint("property_type IN ('apartment', 'house', 'villa', 'cottage', 'cabin', 'guesthouse', 'farmhouse', 'houseboat')", name='ck_listings_property_type'),
    sa.CheckConstraint('bedrooms >= 0 AND beds >= 0 AND bathrooms >= 0', name='ck_listings_rooms'),
    sa.CheckConstraint('cleaning_fee_minor >= 0', name='ck_listings_cleaning_fee'),
    sa.CheckConstraint('max_guests > 0', name='ck_listings_max_guests'),
    sa.CheckConstraint('nightly_price_minor > 0', name='ck_listings_price'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listings_archived_created_id', 'listings', ['archived_at', 'created_at', 'id'], unique=False)
    op.create_index('ix_listings_city', 'listings', ['city'], unique=False)
    op.create_index('ix_listings_host_archived', 'listings', ['host_id', 'archived_at'], unique=False)
    op.create_index('ix_listings_property_type', 'listings', ['property_type'], unique=False)
    op.create_table('listing_amenities',
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('amenity_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id', 'amenity_id')
    )
    op.create_index('ix_listing_amenities_amenity_listing', 'listing_amenities', ['amenity_id', 'listing_id'], unique=False)
    op.create_table('listing_photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=12), server_default='unsplash', nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint("source = 'cloudinary' OR cloudinary_public_id IS NULL", name='ck_listing_photos_public_id'),
    sa.CheckConstraint("source IN ('unsplash', 'cloudinary', 'url')", name='ck_listing_photos_source'),
    sa.CheckConstraint('position >= 0', name='ck_listing_photos_position'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'position', name='uq_listing_photos_position')
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_reviews_rating'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'author_id', name='uq_reviews_listing_author')
    )
    op.create_index('ix_reviews_listing_id', 'reviews', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_listing_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('listing_photos')
    op.drop_index('ix_listing_amenities_amenity_listing', table_name='listing_amenities')
    op.drop_table('listing_amenities')
    op.drop_index('ix_listings_property_type', table_name='listings')
    op.drop_index('ix_listings_host_archived', table_name='listings')
    op.drop_index('ix_listings_city', table_name='listings')
    op.drop_index('ix_listings_archived_created_id', table_name='listings')
    op.drop_table('listings')
    op.drop_table('amenities')
    # ### end Alembic commands ###
