"""bookings

Revision ID: 0004
Revises: 0003
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('guest_id', sa.String(length=36), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), server_default='confirmed', nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('nightly_price_minor', sa.Integer(), nullable=False),
    sa.Column('subtotal_minor', sa.Integer(), nullable=False),
    sa.Column('cleaning_fee_minor', sa.Integer(), nullable=False),
    sa.Column('service_fee_minor', sa.Integer(), nullable=False),
    sa.Column('total_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('listing_title_snapshot', sa.String(length=120), nullable=False),
    sa.Column('location_snapshot', sa.String(length=160), nullable=False),
    sa.Column('cover_photo_snapshot', sa.String(length=500), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("currency = 'INR'", name='ck_bookings_currency'),
    sa.CheckConstraint("status IN ('confirmed')", name='ck_bookings_status'),
    sa.CheckConstraint('check_out > check_in', name='ck_bookings_dates'),
    sa.CheckConstraint('guests > 0 AND nights > 0', name='ck_bookings_counts'),
    sa.CheckConstraint('nightly_price_minor >= 0 AND subtotal_minor >= 0 AND cleaning_fee_minor >= 0 AND service_fee_minor >= 0 AND total_minor >= 0', name='ck_bookings_nonnegative'),
    sa.CheckConstraint('subtotal_minor = nights * nightly_price_minor', name='ck_bookings_subtotal'),
    sa.CheckConstraint('total_minor = subtotal_minor + cleaning_fee_minor + service_fee_minor', name='ck_bookings_total'),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_id', 'idempotency_key', name='uq_bookings_guest_idempotency')
    )
    op.create_index('ix_bookings_guest_check_in_id', 'bookings', ['guest_id', 'check_in', 'id'], unique=False)
    op.create_index('ix_bookings_listing_status_dates', 'bookings', ['listing_id', 'status', 'check_in', 'check_out'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookings_listing_status_dates', table_name='bookings')
    op.drop_index('ix_bookings_guest_check_in_id', table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
